platform :ios, '7.0'
pod 'Reachability',  '~> 3.0.0'
#pod 'JSONModel', '~> 0.11.0'
pod 'AFNetworking', '~> 2.1.0'
pod 'RNBlurModalView', '~> 0.1.0'
pod 'BlocksKit', '~> 2.0.0'
pod 'SVProgressHUD', '~> 1.0'
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'DSBarChart', '~> 0.4.0'
pod 'ViewUtils', '~> 1.1.2'
